resource "sdwan_configuration_group" "example" {
  name        = "TF_Config_Group"
  description = "Generated by Terraform"
  solution    = "sdwan"
  feature_profiles = [
    {
      id = sdwan_system_feature_profile.System_Profile.id
    },
    {
      id = sdwan_transport_feature_profile.Transport_Profile.id
    },
    {
      id = sdwan_service_feature_profile.Service_Profile.id
    }
  ]

}
